# Generated by Django 4.1.3 on 2022-11-15 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('info', models.CharField(default='sample description', max_length=500)),
                ('url', models.CharField(default='/sample_url', max_length=40)),
                ('lnk', models.CharField(default='hi', max_length=1000)),
                ('cOpen', models.DateTimeField(null=True)),
                ('cCLose', models.DateTimeField(null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_img')),
                ('profileSlug', models.SlugField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('p1_high_temp', models.FloatField(default=0, max_length=4)),
                ('p1_tr0', models.FloatField(default=0)),
                ('p1_tr1', models.FloatField(default=0)),
                ('p1_tr2', models.FloatField(default=0)),
                ('p1_tr3', models.FloatField(default=0)),
                ('p1_tr4', models.FloatField(default=0)),
                ('p1_tr5', models.FloatField(default=0)),
                ('p2_low_temp', models.FloatField(default=0, max_length=4)),
                ('p2_tr0', models.FloatField(default=0)),
                ('p2_tr1', models.FloatField(default=0)),
                ('p2_tr2', models.FloatField(default=0)),
                ('p2_tr3', models.FloatField(default=0)),
                ('p2_tr4', models.FloatField(default=0)),
                ('p2_tr5', models.FloatField(default=0)),
                ('p3_high_temp', models.FloatField(default=0, max_length=4)),
                ('p3_tr0', models.FloatField(default=0)),
                ('p3_tr1', models.FloatField(default=0)),
                ('p3_tr2', models.FloatField(default=0)),
                ('p3_tr3', models.FloatField(default=0)),
                ('p3_tr4', models.FloatField(default=0)),
                ('p3_tr5', models.FloatField(default=0)),
                ('p4_low_temp', models.FloatField(default=0, max_length=4)),
                ('p4_tr0', models.FloatField(default=0)),
                ('p4_tr1', models.FloatField(default=0)),
                ('p4_tr2', models.FloatField(default=0)),
                ('p4_tr3', models.FloatField(default=0)),
                ('p4_tr4', models.FloatField(default=0)),
                ('p4_tr5', models.FloatField(default=0)),
                ('contest', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='baseDash.contest')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseDash.profile')),
            ],
        ),
    ]
