# Generated by Django 4.1.3 on 2022-12-08 03:15

import baseDash.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseDash', '0014_contest_isopen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.SlugField(blank=True, default=baseDash.models.generate_slug_code, null=True),
        ),
    ]
