# Generated by Django 4.1.3 on 2022-12-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseDash', '0017_alter_prediction_contest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='overall_score',
            new_name='entry_score',
        ),
        migrations.RemoveField(
            model_name='report',
            name='leaderboard',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='predictions',
            field=models.ManyToManyField(to='baseDash.prediction'),
        ),
        migrations.AddField(
            model_name='score',
            name='leaderboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseDash.leaderboard'),
        ),
    ]
